#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# check for lock file to only run git operations once
if [[ ! -e /lock.file ]]; then
    # Give abc a sudo shell for development
    sed -e 's/# %wheel ALL=(ALL:ALL) NOPASSWD: ALL/%wheel ALL=(ALL:ALL) NOPASSWD: ALL/g' \
        -i /etc/sudoers
    sed -e 's/^wheel:\(.*\)/wheel:\1,abc/g' -i /etc/group
    # create directory for project
    mkdir -p /code
    # make sure URL is set and folder is empty to clone code 
    if [[ ${GITURL+x} ]] && [[ ! "$(/bin/ls -A /code 2>/dev/null)" ]] ; then \
        # clone the url the user passed to this directory
        git clone "${GITURL}" /code
    fi
    lsiown -R abc:abc \
        /code
else
    # lock exists not importing project this is a restart
    echo "Lock exists just starting pylon"
fi

# create lock file after first run
touch /lock.file

# permissions
mkdir -p /config/sessions

lsiown -R abc:abc \
    /config
